/*
  yearly-config.js
  ----------------
  वार्षिक बजेट (Yearly Budget) साठीचा नमुना — चारमाही बजेटच्या config.js पेक्षा वेगळा, पण त्याच
  जनरिक इंजिनवर (app.js) चालतो. लॉगिन नंतर "वार्षिक बजेट" निवडल्यास हा नमुना दाखवला जातो.

  टीप: काही विवरणपत्रे (उदा. Annex 1 - पदांची यादी, Annex 1a, Annex 2क - भाडे तपशील) मूळ
  एक्सेलमध्ये अतिशय गुंतागुंतीची (नावानिहाय, राजपत्रित/अराजपत्रित, स्थायी/अस्थायी अशा अनेक उपवर्गवारीसह)
  आहेत. ती इथे सुलभ करून "dynamic" (युजरला हवे तितके रकाने भरता येतील असे) ठेवली आहेत — मूळ
  एक्सेलमधील सर्व बारीक उपवर्गवारी जशीच्या तशी उतरवलेली नाही. गरज पडल्यास अधिक अचूक बसवून देता येईल.
*/

// चार सामायिक स्तंभ-संच (अनेक विवरणपत्रांत सारखेच रकाने असल्याने पुनर्वापर करतो)
const YEARLY_BUDGET_LINE_COLUMNS = [
  { key: "sr", label: "अ.क्र.", type: "text", editable: false },
  { key: "baab", label: "खर्चाचा तपशील", type: "text", editable: false, width: "20%" },
  { key: "py1", label: "प्रत्यक्ष खर्च 2023-24", type: "number", editable: true },
  { key: "py2", label: "प्रत्यक्ष खर्च 2024-25", type: "number", editable: true },
  { key: "py3", label: "प्रत्यक्ष खर्च 2025-26", type: "number", editable: true },
  { key: "budgetProv", label: "अर्थसंकल्पीय तरतूद 2026-27", type: "number", editable: true },
  { key: "actual4m", label: "चारमाही सुधारित - प्रत्यक्ष खर्च (01.04 ते 31.07.2026)", type: "number", editable: true },
  { key: "expected4m", label: "चारमाही सुधारित - अपेक्षित खर्च (01.08.2026 ते 31.03.2027)", type: "number", editable: true },
  { key: "total4m", label: "एकूण (चारमाही सुधारित)", type: "number", editable: false,
    formula: r => num(r.actual4m) + num(r.expected4m) },
  { key: "nextYear", label: "सन 2027-28 करिता अर्थसंकल्पीय अंदाज", type: "number", editable: true },
];

const YEARLY_ANNEX_CONFIG = [
  // ---------------- Annex 1 : मंजूर पदे व वेतन खर्च (एक्सेलप्रमाणे तंतोतंत — 62 रकाने, 15 स्तंभ) ----------------
  {
    id: "yannex1",
    title: "विवरणपत्र 1 : मंजूर पदे व त्यावर होणारा संभाव्य वेतन खर्च",
    type: "fixed",
    summaryKey: "ekun",
    columns: [
      { key: "sr", label: "अ.क्र.", type: "text", editable: false, width: "5%" },
      { key: "padnaam", label: "पदनाम", type: "text", editable: true, width: "16%" },
      { key: "vetanmatrix", label: "सुधारित वेतनसंरचना (वेतन मॅट्रिक्स)", type: "text", editable: true },
      { key: "manjurPade", label: "एकूण मंजूर पदे", type: "number", editable: true },
      { key: "vetan31mar", label: "मंजूर पदांवर काम करणाऱ्या कर्मचाऱ्यांचे 31.03.2027 रोजीचे वेतन", type: "number", editable: true },
      { key: "naave", label: "मंजूर पदांवर काम करणाऱ्या कर्मचाऱ्यांची नांवे", type: "text", editable: true, width: "12%" },
      { key: "mulVetan", label: "मुळ वेतन", type: "number", editable: true },
      { key: "mahagaiBhatta", label: "महागाई भत्ता", type: "number", editable: true },
      { key: "nps", label: "राष्ट्रीय निवृत्ती वेतन (NPS) 14%", type: "number", editable: true },
      { key: "sthanikPurak", label: "स्थानिक पूरक भत्ता", type: "number", editable: true },
      { key: "gharbhade", label: "घरभाडे भत्ता", type: "number", editable: true },
      { key: "vahtuk", label: "वाहतूक भत्ता", type: "number", editable: true },
      { key: "itarBhatte", label: "इतर भत्ते", type: "number", editable: true },
      { key: "itarKharch", label: "इतर खर्च", type: "number", editable: true },
      { key: "ekun", label: "एकूण (7 ते 14)", type: "number", editable: false,
        formula: r => num(r.mulVetan) + num(r.mahagaiBhatta) + num(r.nps) + num(r.sthanikPurak) +
          num(r.gharbhade) + num(r.vahtuk) + num(r.itarBhatte) + num(r.itarKharch) },
    ],
    rows: [
      { sr: "", padnaam: "स्थायी पदे", isSectionHeader: true },
      { sr: "", padnaam: "कायमपदे (स्थायी )", isSectionHeader: true },
      { sr: "अ", padnaam: "भरलेली राजपत्रीत", isSectionHeader: true },
      { sr: "", padnaam: "1) शिक्षणाधिकारी (माध्यमिक)" },
      { sr: "", padnaam: "2) उपशिक्षणाधिकारी" },
      { sr: "1)", padnaam: "एकुण भरलेली राजपत्रीत (अ)", isSubtotal: true, sumRows: [3, 4] },
      { sr: "ब", padnaam: "भरलेली अराजपत्रीत (एक)(वर्ग 3)", isSectionHeader: true },
      { sr: "", padnaam: "1) सहा. शिक्षण उपनिरीक्षक" },
      { sr: "", padnaam: "2) विषयतज्ञ" },
      { sr: "", padnaam: "3) वरिष्ठ लिपिक" },
      { sr: "", padnaam: "4) रिक्त (वाहन चालक)" },
      { sr: "", padnaam: "एकुण (ब) (एक) भरलेली अराजपत्रीत(वर्ग3)", isSubtotal: true, sumRows: [7, 8, 9, 10] },
      { sr: "क", padnaam: "भरलेली अराजपत्रीत (दोन)(वर्ग 4)", isSectionHeader: true },
      { sr: "", padnaam: "1) पद मंजूर नाही" },
      { sr: "", padnaam: "एकुण (क) (दोन) भरलेली अराजपत्रीत (वर्ग4)", isSubtotal: true, sumRows: [13] },
      { sr: "2)", padnaam: "एकुण भरलेली अराजपत्रीत (ब) + (क)", isSubtotal: true, sumRows: [11, 14] },
      { sr: "3)", padnaam: "एकूण भरलेली स्थायी (1)+(2)", isSubtotal: true, sumRows: [5, 15] },
      { sr: "ड", padnaam: "रिक्त राजपत्रीत", isSectionHeader: true },
      { sr: "", padnaam: "1) रिक्त" },
      { sr: "", padnaam: "2) रिक्त" },
      { sr: "4)", padnaam: "एकुण रिक्त राजपत्रीत (ड)", isSubtotal: true, sumRows: [18, 19] },
      { sr: "इ", padnaam: "रिक्त अराजपत्रीत (एक)(वर्ग 3)", isSectionHeader: true },
      { sr: "", padnaam: "1)" },
      { sr: "", padnaam: "2)" },
      { sr: "", padnaam: "एकुण (इ) (एक) रिक्त अराजपत्रीत (वर्ग3)", isSubtotal: true, sumRows: [22, 23] },
      { sr: "ई", padnaam: "रिक्त अराजपत्रीत (दोन) (वर्ग 4)", isSectionHeader: true },
      { sr: "", padnaam: "1)" },
      { sr: "", padnaam: "2)" },
      { sr: "", padnaam: "एकुण (ई) (दोन) रिक्त अराजपत्रीत(वर्ग4)", isSubtotal: true, sumRows: [26, 27] },
      { sr: "5)", padnaam: "एकुण रिक्त अराजपत्रीत (इ) + (ई)", isSubtotal: true, sumRows: [24, 28] },
      { sr: "6)", padnaam: "एकूण रिक्त स्थायी (4)+(5)", isSubtotal: true, sumRows: [20, 29] },
      { sr: "(A)", padnaam: "एकूण स्थायी पदे  (3)+(6)", isTotalRow: true, sumRows: [16, 30] },
      { sr: "", padnaam: "अस्थायी पदे", isSectionHeader: true },
      { sr: "", padnaam: "कायमपदे (अस्थायी )", isSectionHeader: true },
      { sr: "अ", padnaam: "भरलेली राजपत्रीत", isSectionHeader: true },
      { sr: "", padnaam: "1) शिक्षणाधिकारी (माध्यमिक)" },
      { sr: "", padnaam: "2) उपशिक्षणाधिकारी" },
      { sr: "1)", padnaam: "एकुण भरलेली राजपत्रीत (अ)", isSubtotal: true, sumRows: [35, 36] },
      { sr: "ब", padnaam: "भरलेली अराजपत्रीत (एक)(वर्ग 3)", isSectionHeader: true },
      { sr: "", padnaam: "3) वरिष्ठ लिपिक" },
      { sr: "", padnaam: "एकुण (ब) (एक) भरलेली अराजपत्रीत(वर्ग3)", isSubtotal: true, sumRows: [39] },
      { sr: "क", padnaam: "भरलेली अराजपत्रीत (दोन)(वर्ग 4)", isSectionHeader: true },
      { sr: "", padnaam: "1) पद मंजूर नाही" },
      { sr: "", padnaam: "एकुण (क) (दोन) भरलेली अराजपत्रीत(वर्ग4)", isSubtotal: true, sumRows: [42] },
      { sr: "2)", padnaam: "एकुण भरलेली अराजपत्रीत (ब) + (क)", isSubtotal: true, sumRows: [40, 43] },
      { sr: "3)", padnaam: "एकुण भरलेली अस्थायी (1)+(2)", isSubtotal: true, sumRows: [37, 44] },
      { sr: "ड", padnaam: "रिक्त राजपत्रीत", isSectionHeader: true },
      { sr: "", padnaam: "1)" },
      { sr: "", padnaam: "2)" },
      { sr: "4)", padnaam: "एकुण रिक्त राजपत्रीत (ड)", isSubtotal: true, sumRows: [47, 48] },
      { sr: "इ", padnaam: "रिक्त अराजपत्रीत (एक)(वर्ग 3)", isSectionHeader: true },
      { sr: "", padnaam: "1) सहा. शिक्षण उपनिरीक्षक" },
      { sr: "", padnaam: "2) विषयतज्ञ" },
      { sr: "", padnaam: "3) वाहन चालक" },
      { sr: "", padnaam: "एकुण (इ) (एक) रिक्त अराजपत्रीत(वर्ग3)", isSubtotal: true, sumRows: [51, 52, 53] },
      { sr: "ई", padnaam: "रिक्त अराजपत्रीत (दोन)(वर्ग 4)", isSectionHeader: true },
      { sr: "", padnaam: "1) पद मंजूर नाही" },
      { sr: "", padnaam: "एकुण (ई) (दोन) रिक्त अराजपत्रीत(वर्ग4)", isSubtotal: true, sumRows: [56] },
      { sr: "5)", padnaam: "एकुण रिक्त अराजपत्रीत (इ) + (ई)", isSubtotal: true, sumRows: [54, 57] },
      { sr: "6)", padnaam: "एकूण रिक्त अस्थायी (4)+(5)", isSubtotal: true, sumRows: [49, 58] },
      { sr: "(B)", padnaam: "एकूण अस्थायी पदे (3)+(6)", isTotalRow: true, sumRows: [45, 59] },
      { sr: "", padnaam: "एकूण (A)+ (B)", isTotalRow: true, sumRows: [31, 60] },
    ],
  },

  // ---------------- Annex 1अ : अस्थायी राजपत्रित/अराजपत्रित पदांची संख्या व वेतन तरतूद (एक्सेलप्रमाणे — 13 रकाने) ----------------
  {
    id: "yannex1a",
    title: "विवरणपत्र 1अ : अस्थायी राजपत्रित/अराजपत्रित पदांची संख्या व वेतन तरतूद",
    type: "fixed",
    summaryKey: "ekun",
    columns: [
      { key: "sr", label: "प्रधान शिर्ष गौण आणि उपशिर्ष", type: "text", editable: false, width: "6%" },
      { key: "padnaam", label: "वेतनश्रेणी", type: "text", editable: true, width: "22%" },
      { key: "sankhya", label: "अधिकारी/कर्मचारी संख्या", type: "number", editable: true },
      { key: "vetanTartud", label: "प्रत्येक संवर्गाच्या वेतनासाठी असलेली एकूण तरतूद", type: "number", editable: true },
      { key: "mahagaiTartud", label: "प्रत्येक संवर्गाच्या महागाई भत्यासाठी असलेली एकूण तरतूद", type: "number", editable: true },
      { key: "ekun", label: "एकूण", type: "number", editable: false,
        formula: r => num(r.vetanTartud) + num(r.mahagaiTartud) },
      { key: "shera", label: "शेरा", type: "text", editable: true },
    ],
    rows: [
      { sr: "अ)", padnaam: "अ) पुढील रकमेत वेतन घेणारे अधिकारी/कर्मचारी (राजपत्रित)", isSectionHeader: true },
      { sr: "", padnaam: "1) शिक्षणाधिकारी" },
      { sr: "", padnaam: "2) उपशिक्षणाधिकारी" },
      { sr: "", padnaam: "एकूण (अ)", isSubtotal: true, sumRows: [1, 2] },
      { sr: "ब)", padnaam: "ब) पुढील रकमेत वेतन घेणारे अधिकारी/कर्मचारी (वर्ग 3)", isSectionHeader: true },
      { sr: "", padnaam: "1) वरिष्ठ लिपिक" },
      { sr: "", padnaam: "2)" },
      { sr: "", padnaam: "एकूण (ब)", isSubtotal: true, sumRows: [5, 6] },
      { sr: "क)", padnaam: "क) पुढील रकमेत वेतन घेणारे अधिकारी/कर्मचारी (वर्ग 4)", isSectionHeader: true },
      { sr: "", padnaam: "1) पद मंजूर नाही" },
      { sr: "", padnaam: "2) पद मंजूर नाही" },
      { sr: "", padnaam: "एकूण (क)", isSubtotal: true, sumRows: [9, 10] },
      { sr: "", padnaam: "एकूण बेरीज (अ+ब+क)", isTotalRow: true, sumRows: [3, 7, 11] },
    ],
  },

  // ---------------- Annex 2 : अर्थसंकल्पीय अंदाज ----------------
  {
    id: "yannex2",
    title: "विवरणपत्र 2 : अर्थसंकल्पीय अंदाज सन 2027-28",
    type: "fixed",
    summaryKey: "nextYear",
    columns: YEARLY_BUDGET_LINE_COLUMNS,
    rows: [
      { sr: "1", baab: "01 वेतन" },
      { sr: "2", baab: "02 मजूरी" },
      { sr: "3", baab: "03 अतिकालीक भत्ता" },
      { sr: "4", baab: "05 बक्षिसे" },
      { sr: "5", baab: "06 दूरध्वनी, वीज व पाणी" },
      { sr: "6", baab: "10 कंत्राटी सेवा" },
      { sr: "7", baab: "11 प्रवास खर्च" },
      { sr: "8", baab: "13 कार्यालयीन खर्च" },
      { sr: "9", baab: "14 भाडेपट्टी व कर" },
      { sr: "10", baab: "16 प्रकाशने" },
      { sr: "11", baab: "17 संगणक खर्च" },
      { sr: "12", baab: "19 आहार खर्च" },
      { sr: "13", baab: "21 सामुग्री व पुरवठा" },
      { sr: "14", baab: "24 पेट्रोल तेल व वंगण" },
      { sr: "15", baab: "26 जाहीरात व प्रकाशन खर्च" },
      { sr: "16", baab: "आतिथ्य खर्च/आतिथ्य भत्ते" },
      { sr: "17", baab: "27 प्रधान/गौण बांधकामे" },
      { sr: "18", baab: "28 व्यावसायिक व विशेष सेवाकरिता द्यावयाची रक्कम" },
      { sr: "19", baab: "31 सहाय्यक अनुदाने/अंशदाने/अर्थसहाय्य" },
      { sr: "20", baab: "34 शिष्यवृत्या व विद्यावेतने" },
      { sr: "21", baab: "50 इतर खर्च" },
      { sr: "22", baab: "51 मोटार वाहने" },
      { sr: "23", baab: "52 यंत्रसामग्री व साधनसामुग्री, अवजारे व संयत्र" },
      { sr: "", baab: "एकूण बेरीज", isTotalRow: true,
        sumRows: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22] },
    ],
  },

  // ---------------- Annex 2अ : 06 दूरध्वनी, वीज व पाणी तपशील ----------------
  {
    id: "yannex2a",
    title: "विवरणपत्र 2अ : 06 दूरध्वनी, वीज व पाणी याचा तपशील",
    type: "fixed",
    summaryKey: "nextYear",
    columns: YEARLY_BUDGET_LINE_COLUMNS,
    rows: [
      { sr: "1", baab: "विद्युत खर्च" },
      { sr: "2", baab: "दूरध्वनी खर्च" },
      { sr: "3", baab: "पाणीपट्टी खर्च" },
      { sr: "", baab: "एकूण खर्च", isTotalRow: true, sumRows: [0,1,2] },
    ],
  },

  // ---------------- Annex 2ब : कार्यालयीन खर्चाचा तपशील ----------------
  {
    id: "yannex2b",
    title: "विवरणपत्र 2ब : कार्यालयीन खर्चाचा तपशील",
    type: "fixed",
    summaryKey: "nextYear",
    columns: YEARLY_BUDGET_LINE_COLUMNS,
    rows: [
      { sr: "1", baab: "वायु इंधन खर्च" },
      { sr: "2", baab: "उष्ण व शीत हवामान विषयक खर्च" },
      { sr: "3", baab: "वाचनालय" },
      { sr: "4", baab: "लेखन सामग्री" },
      { sr: "5", baab: "प्रयोगशाळा" },
      { sr: "6", baab: "कार्यालयीन यंत्राची व उपकरणाची खरेदी आणि परिरक्षण" },
      { sr: "7", baab: "टपाल खर्च" },
      { sr: "8", baab: "फर्निचर खरेदी" },
      { sr: "9", baab: "फर्निचर दुरुस्ती" },
      { sr: "10", baab: "नमुने छपाई" },
      { sr: "11", baab: "वाहनांचे परिरक्षण" },
      { sr: "", baab: "एकूण", isTotalRow: true, sumRows: [0,1,2,3,4,5,6,7,8,9,10] },
    ],
  },

  // ---------------- Annex 2क : इमारत भाडेबाबतचा तपशील (एक्सेलप्रमाणे — 15 स्तंभ, 2 रकाने) ----------------
  {
    id: "yannex2c",
    title: "विवरणपत्र 2क : इमारत भाडेबाबतचा तपशील",
    type: "fixed",
    note: "मूळ एक्सेल फाईलमध्ये या विवरणपत्रासाठी अनेक अपुरे/जुने नमुने (draft) सापडले — त्यातील सर्वात पूर्ण असलेली रचना (15 स्तंभ, 'नियमित भाडे'/'थकीत भाडे' अशी 2 रकाने) इथे तंतोतंत वापरली आहे.",
    summaryKey: "nextYear",
    columns: [
      { key: "sr", label: "अ.क्र.", type: "text", editable: false },
      { key: "vibhag", label: "विभागाचे नाव", type: "text", editable: true },
      { key: "karyalay", label: "कार्यालयाचे नाव", type: "text", editable: true },
      { key: "prakar", label: "प्रकार", type: "text", editable: false, width: "10%" },
      { key: "tapshil", label: "भाडेतत्वावर कार्यालय कार्यरत असलेल्या इमारतीचा तपशील", type: "text", editable: true },
      { key: "kshetrafal", label: "सा.बा.विभागाने निर्धारित केलेले क्षेत्रफळ", type: "text", editable: true },
      { key: "bhaadeKalavadhi", label: "सा.बा.विभागाने भाडे निर्धारित केलेला कालावधी", type: "text", editable: true },
      { key: "bhaadePratimaha", label: "सा.बा.विभागाने निर्धारित केलेले भाडे प्रति महा (रक्कम रु.)", type: "number", editable: true },
      { key: "budgetProv", label: "सन 2026-27 करीता लागणारी एकूण तरतूद", type: "number", editable: true },
      { key: "tartudKalavadhi", label: "सन 2026-27 तरतूदीचा कालावधी (माहे-ते-माहे)", type: "text", editable: true },
      { key: "thakitKaran", label: "भाडे/कर थकीत राहण्याची कारणे", type: "text", editable: true },
      { key: "actual4m", label: "प्रत्यक्ष खर्च कालावधी 01/04/2026 ते 31/07/2026", type: "number", editable: true },
      { key: "expected4m", label: "संभाव्य खर्च 01/08/2026 ते 31/03/2027", type: "number", editable: true },
      { key: "total4m", label: "एकूण खर्च 2026-27 (12+13)", type: "number", editable: false,
        formula: r => num(r.actual4m) + num(r.expected4m) },
      { key: "nextYear", label: "सन 2027-28 करिता अर्थसंकल्पीय अंदाज", type: "number", editable: true },
    ],
    rows: [
      { sr: "1", prakar: "नियमित भाडे" },
      { sr: "2", prakar: "थकीत भाडे" },
    ],
  },

  // ---------------- Annex 3 : अशासकीय संस्थांना वेतन व वेतनेतर अनुदान ----------------
  {
    id: "yannex3",
    title: "विवरणपत्र 3 : अशासकीय संस्थांना वेतन व वेतनेतर अनुदान",
    type: "fixed",
    summaryKey: "nextYear",
    columns: YEARLY_BUDGET_LINE_COLUMNS,
    rows: [
      { sr: "1", baab: "मूळ वेतन" },
      { sr: "2", baab: "महागाई भत्ता" },
      { sr: "3", baab: "राष्ट्रीय निवृत्ती वेतन (NPS) 14%" },
      { sr: "4", baab: "घरभाडे भत्ता" },
      { sr: "5", baab: "शहरपूरक भत्ता" },
      { sr: "6", baab: "वाहतूक भत्ता" },
      { sr: "7", baab: "थकीत वेतन" },
      { sr: "", baab: "एकूण वेतन (1 ते 7)", isSubtotal: true, sumRows: [0,1,2,3,4,5,6] },
      { sr: "", baab: "वेतनेतर तरतुद" },
      { sr: "", baab: "एकूण (वेतन + वेतनेतर)", isTotalRow: true, sumRows: [7,8] },
    ],
  },

  // ---------------- Annex 3अ : 31 सहायक अनुदाने तपशील ----------------
  {
    id: "yannex3a",
    title: "विवरणपत्र 3अ : 31 सहायक अनुदाने उद्दिष्टांतर्गत आवश्यक तरतूद तपशील",
    type: "keyvalue",
    fields: [
      { key: "travel4m", label: "प्रवास खर्च (चारमाही सुधारित अंदाज 2026-27)", type: "text" },
      { key: "office4m", label: "कार्यालयीन खर्च (चारमाही सुधारित अंदाज 2026-27)", type: "text" },
      { key: "rent4m", label: "भाडेपट्टी व कर (चारमाही सुधारित अंदाज 2026-27)", type: "text" },
      { key: "nonSalary4m", label: "वेतनेतर (चारमाही सुधारित अंदाज 2026-27)", type: "text" },
      { key: "peon4m", label: "शिपाई भत्ता (चारमाही सुधारित अंदाज 2026-27)", type: "text" },
      { key: "thakit4m", label: "थकीत (चारमाही सुधारित अंदाज 2026-27)", type: "text" },
      { key: "other4m", label: "इतर (चारमाही सुधारित अंदाज 2026-27)", type: "text" },
      { key: "ekun4m", label: "एकूण (चारमाही सुधारित अंदाज 2026-27)", type: "text" },
      { key: "travelNext", label: "प्रवास खर्च (अर्थसंकल्पीय अंदाज 2027-28)", type: "text" },
      { key: "officeNext", label: "कार्यालयीन खर्च (अर्थसंकल्पीय अंदाज 2027-28)", type: "text" },
      { key: "rentNext", label: "भाडेपट्टी व कर (अर्थसंकल्पीय अंदाज 2027-28)", type: "text" },
      { key: "nonSalaryNext", label: "वेतनेतर (अर्थसंकल्पीय अंदाज 2027-28)", type: "text" },
    ],
  },

  // ---------------- Annex 3ब : शाळानिहाय वेतन अनुदान तरतूद ----------------
  {
    id: "yannex3b",
    title: "विवरणपत्र 3ब : शाळानिहाय वेतनासाठी आवश्यक तरतूद",
    type: "dynamic",
    addRowLabel: "नवीन शाळा जोडा",
    columns: [
      { key: "sr", label: "अ.क्र.", type: "text", editable: false, auto: "serial" },
      { key: "jilha", label: "जिल्हा", type: "text", editable: true },
      { key: "udise", label: "शाळेचा युडायस क्रमांक", type: "text", editable: true },
      { key: "shala", label: "शाळेचे नाव", type: "text", editable: true, width: "18%" },
      { key: "manjur", label: "मंजूर पदे", type: "number", editable: true },
      { key: "karyarat", label: "कार्यरत पदे", type: "number", editable: true },
      { key: "rikt", label: "रिक्त पदे", type: "number", editable: true },
      { key: "vetanTartud", label: "वेतनासाठी तरतूद (3अ नुसार)", type: "number", editable: true },
      { key: "thakitTartud", label: "थकीत असल्यास तरतूद", type: "number", editable: true },
      { key: "ekun", label: "एकूण आवश्यक तरतूद", type: "number", editable: false,
        formula: r => num(r.vetanTartud) + num(r.thakitTartud) },
    ],
    rows: [],
    summaryKey: "ekun",
  },

  // ---------------- Annex 3क : वर्षनिहाय मंजूर पदांचा इतिहास ----------------
  {
    id: "yannex3c",
    title: "विवरणपत्र 3क : कार्यक्रमांतर्गत मंजूर करण्यात आलेल्या पदांचा वर्षनिहाय तपशील",
    type: "fixed",
    note: "टीप- शासन निर्णयाच्या प्रती या तक्त्यासोबत जोडणे आवश्यक आहे.",
    summaryKey: "prataksh",
    columns: [
      { key: "yojana", label: "योजनेचे नांव", type: "text", editable: true, width: "14%" },
      { key: "sn", label: "सन", type: "text", editable: false },
      { key: "padnaam", label: "पदनाम", type: "text", editable: true, width: "14%" },
      { key: "vetanshreni", label: "वेतनश्रेणी", type: "text", editable: true },
      { key: "manjur", label: "एकूण मंजूर पदे", type: "number", editable: true },
      { key: "bharleli", label: "भरलेली", type: "number", editable: true },
      { key: "rikt", label: "रिक्त", type: "number", editable: true },
      { key: "prataksh", label: "प्रत्यक्ष खर्च", type: "number", editable: true },
      { key: "sasanNirnay", label: "शासन निर्णय क्रमांक व दिनांक", type: "text", editable: true },
      { key: "shera", label: "शेरा", type: "text", editable: true },
    ],
    rows: [
      { sn: "2019-2020" }, { sn: "2020-2021" }, { sn: "2021-2022" }, { sn: "2022-2023" },
      { sn: "2023-2024" }, { sn: "2024-2025" }, { sn: "2025-2026" }, { sn: "2026-2027" },
      { sn: "एकूण", isTotalRow: true, sumRows: [0,1,2,3,4,5,6,7] },
    ],
  },

  // ---------------- Annex 4 : वैधानिक विकास मंडळनिहाय वाटप ----------------
  {
    id: "yannex4",
    title: "विवरणपत्र 4 : वैधानिक विकास मंडळनिहाय तरतूदीचे वाटप",
    type: "dynamic",
    addRowLabel: "नवीन लेखाशीर्ष जोडा",
    columns: [
      { key: "sr", label: "अ.क्र.", type: "text", editable: false, auto: "serial" },
      { key: "lekhashirsha", label: "लेखाशिर्ष", type: "text", editable: true },
      { key: "prastavit", label: "प्रस्तावित तरतूद", type: "number", editable: true },
      { key: "vidarbha", label: "विदर्भ वैधानिक विकास मंडळ", type: "number", editable: true },
      { key: "marathwada", label: "मराठवाडा विकास मंडळ", type: "number", editable: true },
      { key: "urvarit", label: "उर्वरित महाराष्ट्र वैधानिक विकास मंडळ", type: "number", editable: true },
      { key: "avibhajya", label: "अविभाज्य", type: "number", editable: true },
      { key: "ekun", label: "एकूण प्रस्तावित तरतूद", type: "number", editable: false,
        formula: r => num(r.vidarbha) + num(r.marathwada) + num(r.urvarit) + num(r.avibhajya) },
    ],
    rows: [{}],
    summaryKey: "ekun",
  },

  // ---------------- Annex 5 : मासिक निधी विवरणपत्र ----------------
  {
    id: "yannex5",
    title: "विवरणपत्र 5 : प्रस्तावित तरतूदीचे मासिक निधी विवरणपत्र",
    type: "fixed",
    summaryKey: "prastavit",
    columns: [
      { key: "sr", label: "अ.क्र.", type: "text", editable: false },
      { key: "uddishtha", label: "उद्दिष्ट", type: "text", editable: false, width: "14%" },
      { key: "prastavit", label: "प्रस्तावित तरतूद", type: "number", editable: true },
      { key: "m1", label: "एप्रिल", type: "number", editable: true },
      { key: "m2", label: "मे", type: "number", editable: true },
      { key: "m3", label: "जुन", type: "number", editable: true },
      { key: "m4", label: "जुलै", type: "number", editable: true },
      { key: "m5", label: "ऑगस्ट", type: "number", editable: true },
      { key: "m6", label: "सप्टेंबर", type: "number", editable: true },
      { key: "m7", label: "ऑक्टोबर", type: "number", editable: true },
      { key: "m8", label: "नोव्हेंबर", type: "number", editable: true },
      { key: "m9", label: "डिसेंबर", type: "number", editable: true },
      { key: "m10", label: "जानेवारी", type: "number", editable: true },
      { key: "m11", label: "फेब्रुवारी", type: "number", editable: true },
      { key: "m12", label: "मार्च", type: "number", editable: true },
      { key: "total", label: "एकूण (12 महिने)", type: "number", editable: false,
        formula: r => ["m1","m2","m3","m4","m5","m6","m7","m8","m9","m10","m11","m12"]
          .reduce((s,k) => s + num(r[k]), 0) },
    ],
    rows: [
      { sr: "1", uddishtha: "01 वेतन" },
      { sr: "2", uddishtha: "02 मजूरी" },
      { sr: "3", uddishtha: "03 अतिकालीक भत्ता" },
      { sr: "4", uddishtha: "05 बक्षिसे" },
      { sr: "5", uddishtha: "06 दूरध्वनी, वीज व पाणी" },
      { sr: "6", uddishtha: "10 कंत्राटी सेवा" },
      { sr: "7", uddishtha: "11 प्रवास खर्च" },
      { sr: "8", uddishtha: "13 कार्यालयीन खर्च" },
      { sr: "9", uddishtha: "14 भाडेपट्टी व कर" },
      { sr: "10", uddishtha: "16 प्रकाशने" },
      { sr: "11", uddishtha: "17 संगणक खर्च" },
      { sr: "12", uddishtha: "19 आहार खर्च" },
      { sr: "13", uddishtha: "21 सामुग्री व पुरवठा" },
      { sr: "14", uddishtha: "24 पेट्रोल तेल व वंगण" },
      { sr: "15", uddishtha: "26 जाहीरात व प्रकाशन खर्च" },
      { sr: "16", uddishtha: "आतिथ्य खर्च/आतिथ्य भत्ते" },
      { sr: "17", uddishtha: "27 प्रधान/गौण बांधकामे" },
      { sr: "18", uddishtha: "28 व्यावसायिक व विशेष सेवाकरिता द्यावयाची रक्कम" },
      { sr: "19", uddishtha: "31 सहाय्यक अनुदाने/अंशदाने/अर्थसहाय्य" },
      { sr: "20", uddishtha: "34 शिष्यवृत्या व विद्यावेतने" },
      { sr: "21", uddishtha: "50 इतर खर्च" },
      { sr: "22", uddishtha: "51 मोटार वाहने" },
      { sr: "23", uddishtha: "52 यंत्रसामग्री व साधनसामुग्री, अवजारे व संयत्र" },
      { sr: "", uddishtha: "एकूण", isTotalRow: true,
        sumRows: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22] },
    ],
  },

  // ---------------- Annex 6 : योजना/लेखाशिर्षाबाबतची माहिती ----------------
  {
    id: "yannex6",
    title: "विवरणपत्र 6 : योजना/लेखाशिर्षाबाबतची माहिती",
    type: "keyvalue",
    fields: [
      { key: "lekhashirsha_naav", label: "1. लेखाशिर्षाचे नाव", type: "text" },
      { key: "swaroop", label: "2. योजनेचे स्वरुप", type: "text" },
      { key: "uddesh", label: "3. योजनेचा उद्देश", type: "text" },
      { key: "amalbajavani", label: "4. अंमलबजावणीची कार्यपध्दती", type: "textarea" },
      { key: "shasan_nirnay", label: "5. योजनेचे शासन निर्णय", type: "text" },
      { key: "savistar_tapshil", label: "6. योजनेबाबतचा सविस्तर तपशील", type: "textarea" },
      { key: "pade_sthiti", label: "7. सदर योजनेमधील मंजूर/कार्यरत/रिक्त पदे", type: "textarea" },
    ],
  },

  // ---------------- Annex 7 : भविष्य निर्वाह निधी व्याजप्रदान ----------------
  {
    id: "yannex7",
    title: "विवरणपत्र 7 : भविष्य निर्वाह निधी व्याजप्रदान (प्रधान लेखाशीर्ष 2049)",
    type: "fixed",
    note: "प्रत्येक योजनेकरिता स्वतंत्र विवरणपत्र वापरावे (उदा. सहाय्यित अशासकीय माध्यमिक/विशेष शाळा भ.नि.नि. आणि खाजगी प्राथमिक शाळा भ.नि.नि. यांसाठी वेगवेगळे भरा).",
    summaryKey: "val",
    columns: [
      { key: "sr", label: "अ.क्र.", type: "text", editable: false },
      { key: "baab", label: "तपशील", type: "text", editable: false, width: "40%" },
      { key: "val", label: "रक्कम रुपये हजारात", type: "text", editable: true, summable: true },
    ],
    rows: [
      { sr: "", baab: "योजनेचे नांव" },
      { sr: "", baab: "खातेदार संख्या - शिक्षक" },
      { sr: "", baab: "खातेदार संख्या - शिक्षकेतर" },
      { sr: "", baab: "खातेदार संख्या - एकूण", isSubtotal: true, sumRows: [1, 2] },
      { sr: "1", baab: "दिनांक 01/04/2027 ची अपेक्षित शिल्लक" },
      { sr: "2", baab: "सन 2027-28 ची संभाव्य जमा" },
      { sr: "3", baab: "सन 2027-28 मधील संभाव्य उचल" },
      { sr: "4", baab: "दिनांक 31/03/2028 ची संभाव्य जमा (2-3)",
        crossFormulaCol: "val", crossFormula: rows => num(rows[5].val) - num(rows[6].val) },
      { sr: "5", baab: "जमा रकमेवर 3.55% व्याज (अ.क्र.4 वर)",
        crossFormulaCol: "val", crossFormula: rows => num(rows[7].val) * 0.0355 },
      { sr: "6", baab: "आरंभीच्या शिलकेवर 7.10% दराने व्याज (अ.क्र.1 वर)",
        crossFormulaCol: "val", crossFormula: rows => num(rows[4].val) * 0.071 },
      { sr: "7", baab: "एकूण संभाव्य देय व्याज (5+6)",
        crossFormulaCol: "val", crossFormula: rows => num(rows[8].val) + num(rows[9].val) },
      { sr: "8", baab: "दिनांक 31/03/2028 अखेर संभाव्य अंतिम शिल्लक (1+4+7)",
        crossFormulaCol: "val", crossFormula: rows => num(rows[4].val) + num(rows[7].val) + num(rows[10].val) },
    ],
  },

  // ---------------- Annex 8 : जमा अंदाज ----------------
  {
    id: "yannex8",
    title: "विवरणपत्र 8 : जमा अंदाज सन 2027-28",
    type: "fixed",
    summaryKey: "nextYear",
    columns: [
      { key: "sr", label: "क्रमांक", type: "text", editable: false },
      { key: "baab", label: "जमेची बाजू", type: "text", editable: false, width: "34%" },
      { key: "py1", label: "प्रत्यक्ष जमा 2023-24", type: "number", editable: true },
      { key: "py2", label: "प्रत्यक्ष जमा 2024-25", type: "number", editable: true },
      { key: "py3", label: "प्रत्यक्ष जमा 2025-26", type: "number", editable: true },
      { key: "budgetProv", label: "अर्थसंकल्प जमा सन 2026-27", type: "number", editable: true },
      { key: "revised4m", label: "एकूण संभाव्य जमा (चारमाही सुधारित अंदाजाप्रमाणे)", type: "number", editable: true },
      { key: "nextYear", label: "प्रस्तावित अर्थसंकल्प जमा अंदाज सन 2027-28", type: "number", editable: true },
    ],
    rows: [
      { sr: "", baab: "0202 शिक्षण क्रीडा, कला व संस्कृती — 101 प्राथमिक शिक्षण", isSectionHeader: true },
      { sr: "", baab: "(01) शिक्षण फी व इतर फी", isSectionHeader: true },
      { sr: "1", baab: "(01)(01) शिक्षण फी व इतर फी (02020204)" },
      { sr: "2", baab: "(01)(02) शिक्षण फी व इतर फी (02020213)" },
      { sr: "3", baab: "(02)(01) 25% राखीव प्रवेश - केंद्र शासन प्रतिपुर्ती (02025046)" },
      { sr: "", baab: "एकूण शिक्षण फी व इतर", isSubtotal: true, sumRows: [2,3,4] },
      { sr: "", baab: "102, माध्यमिक शिक्षण", isSectionHeader: true },
      { sr: "", baab: "(01) शिक्षण फी व इतर फी", isSectionHeader: true },
      { sr: "4", baab: "(01)(01) परीक्षा फी (02020222)" },
      { sr: "5", baab: "(1)(02) शिक्षण फी व इतर फी (02020231)" },
      { sr: "6", baab: "(01)(03) दंड व जप्तीच्या रकमा (02020242)" },
      { sr: "", baab: "एकूण 102 शिक्षण फी व इतर फी", isSubtotal: true, sumRows: [8,9,10] },
      { sr: "", baab: "104 प्रौढ शिक्षण", isSectionHeader: true },
      { sr: "", baab: "(01) शिक्षण फी व इतर फी", isSectionHeader: true },
      { sr: "7", baab: "(01)(01) परीक्षा फी (02020278)" },
      { sr: "8", baab: "(01)(03) शिक्षण फी व इतर फी (02020287)" },
      { sr: "", baab: "एकूण प्रौढ शिक्षण व इतर फी", isSubtotal: true, sumRows: [14,15] },
      { sr: "", baab: "501 सेवा व सेवा फी", isSectionHeader: true },
      { sr: "9", baab: "(00)(01) सेवा व सेवा फी (02020062)" },
      { sr: "10", baab: "(00)(02) महा. शैक्षणिक संस्था शुल्क विनिमयन अधि. 2011 (शुल्क निर्धारण) (02025028)" },
      { sr: "", baab: "एकूण 501 सेवा व सेवा फी", isSubtotal: true, sumRows: [18,19] },
      { sr: "", baab: "600 सर्वसाधारण", isSectionHeader: true },
      { sr: "", baab: "(01) सर्वसाधारण", isSectionHeader: true },
      { sr: "11", baab: "(01)(01) परीक्षा फी (02020296)" },
      { sr: "12", baab: "(01)(02) दान निधीतून मिळणारी अंशदाने व उत्पन्न (02020302)" },
      { sr: "13", baab: "(01)(03) महा. पूर्वमाध्यमिक अधि. 1996 - शालेय पूर्व केंद्रापासून मिळणारी नोंदणी फी (02020311)" },
      { sr: "", baab: "एकूण 600 सर्वसाधारण", isSubtotal: true, sumRows: [23,24,25] },
      { sr: "", baab: "800 इतर जमा रकमा", isSectionHeader: true },
      { sr: "", baab: "(01) इतर जमा रकमा", isSectionHeader: true },
      { sr: "14", baab: "(01)(01) अतिप्रदानाची वसूली (02020322)" },
      { sr: "15", baab: "(01)(02) रजावेतने अंशदाने (02020331)" },
      { sr: "16", baab: "(01)(03) वस्तूसंग्रह/रद्दी/इतर विक्री (02020349)" },
      { sr: "17", baab: "(01)(04) इतर बाबी (02020358)" },
      { sr: "18", baab: "(01)(06) माध्यमिक शाळा परीक्षा मंडळाकडून वसूली (02020376)" },
      { sr: "19", baab: "(01)(07) अनधिकृत नगरपालिकांकडून वसुली (02020385)" },
      { sr: "20", baab: "(01)(08) संकीर्ण (02020394)" },
      { sr: "", baab: "एकूण 800 (01)", isSubtotal: true, sumRows: [29,30,31,32,33,34,35] },
      { sr: "21", baab: "(02)(01) महाराष्ट्र राज्य परीक्षा परिषदेकडून वसुली (02020198)" },
      { sr: "", baab: "एकूण 800 जमा रकमा", isSubtotal: true, sumRows: [36,37] },
      { sr: "", baab: "801 अनुदानग्राहीकडून अखर्चित शिल्लकीवरील व्याज किंवा इतर जमा रकमा", isSectionHeader: true },
      { sr: "22", baab: "(01) व्याज - सिंगल नोडल खात्यातील अखर्चित शिल्लकीवरील व्याज (02025091)" },
      { sr: "23", baab: "(02) इतर जमा रकमा - सिंगल नोडल खात्यातील इतर जमा रकमा (02025108)" },
      { sr: "", baab: "एकूण 801 व्याज किंवा इतर जमा रकमा", isSubtotal: true, sumRows: [40,41] },
      { sr: "", baab: "एकूण 01 सर्वसाधारण शिक्षण", isTotalRow: true, sumRows: [5,11,16,20,26,38,42] },
    ],
  },
];

if (typeof window !== "undefined") {
  window.YEARLY_ANNEX_CONFIG = YEARLY_ANNEX_CONFIG;
}
